### ISSUE TITLE
Checklist for helping to decide when software is "ready to release"

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-NRI/dev-docs#13]
In a recent ACCESSS-NRI skillshare we discussed the process around releasing ACCESS-NRI tools/software to the community. The following were considered important when deciding whether something is "ready for release":

- [ ] well documented (including examples/tutorials)
- [ ] well tested (ideally automatically in CI)
- [ ] easily installable (e.g. from `accessnri` conda channel)
- [ ] automated (or well documented) release process
- [ ] internally reviewed, tested and approved
- [ ] open (where possible) and version controlled codebase (e.g. on GitHub)
- [ ] if on GitHub or similar, a clear README with links to docs and other relevant info (badges can be nice here).
- [ ] recommendations on how to acknowledge/cite (perhaps a DOI via Zenodo)
- [ ] effective way to receive feedback (e.g. templated GitHub issues)
- [ ] clear acknowledgement of previous work where relevant

Please feel free to add/discuss

**Comment by truth-quark** [comment]
What about adding unit test coverage to the list?

**Comment by anton-seaice** [comment]
I would also add "Known Issues Documented"
